# Generated by Django 4.2 on 2023-04-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phonenumber', models.IntegerField()),
                ('carname', models.CharField(default=3, max_length=30)),
                ('numpalte', models.IntegerField()),
                ('date', models.IntegerField(max_length=30)),
                ('client', models.CharField(max_length=30)),
                ('phonenum', models.IntegerField()),
            ],
        ),
    ]
